/**
 * Build the hosted copy: one HTML file, no server, nothing fetched.
 *
 *   node web/build.mjs           → dist/elbi.html
 *
 * It is the real app, not a rewrite of it. The same markup, the same stylesheet
 * and the same modules go in; only api.js is swapped for the browser-side stand-in
 * in web/api.web.js, and the sample clips are carried inside the page instead of
 * being read off a disk. When public/js changes, this changes with it.
 *
 * The three things that genuinely need a machine of your own — scanning a folder,
 * adding a source by URL, and the Internet Archive — are taken out of the markup
 * here rather than left to fail when tapped.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { bundle } from './bundle.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PUBLIC = path.join(ROOT, 'public');
const MEDIA = path.join(ROOT, 'web', 'sample', 'media');
const OUT = path.join(ROOT, 'dist', 'elbi.html');

const read = (...parts) => fs.readFileSync(path.join(...parts), 'utf8');
const b64 = (...parts) => fs.readFileSync(path.join(...parts)).toString('base64');

// --------------------------------------------------------------------------
// the sample media, as one module of base64

const MIME = { '.webm': 'video/webm', '.jpg': 'image/jpeg', '.png': 'image/png' };

function mediaModule() {
  const entries = fs.readdirSync(MEDIA).filter((f) => MIME[path.extname(f)]).sort();
  const lines = entries.map((name) => {
    const bytes = fs.readFileSync(path.join(MEDIA, name));
    return `  ${JSON.stringify(name)}: { type: ${JSON.stringify(MIME[path.extname(name)])}, `
      + `size: ${bytes.length}, b64: ${JSON.stringify(bytes.toString('base64'))} },`;
  });
  return {
    source: `/** Sample clips and artwork, carried inside the page. Generated by web/build.mjs. */\nexport const MEDIA = {\n${lines.join('\n')}\n};\n`,
    bytes: entries.reduce((n, name) => n + fs.statSync(path.join(MEDIA, name)).size, 0),
    count: entries.length,
  };
}

// --------------------------------------------------------------------------
// css and markup

function styles() {
  let css = read(PUBLIC, 'css', 'elbi.css');
  for (const font of fs.readdirSync(path.join(PUBLIC, 'fonts')).filter((f) => f.endsWith('.woff2'))) {
    css = css.replaceAll(`url('/fonts/${font}')`, `url(data:font/woff2;base64,${b64(PUBLIC, 'fonts', font)})`);
  }
  if (css.includes('/fonts/')) throw new Error('a font reference was left pointing at the server');
  // The host page paints its own ground behind an artifact, and its reset asks
  // for light form controls. Elbi is a dark room; say so before anything else.
  return `:root { color-scheme: dark; }\n${css}`;
}

function markup() {
  const html = read(PUBLIC, 'index.html');
  let body = html.slice(html.indexOf('<body>') + '<body>'.length, html.lastIndexOf('</body>'));

  // The app is loaded as one inline script instead.
  body = body.replace(/<script type="module"[^>]*><\/script>/, '');

  const icon = `data:image/png;base64,${b64(PUBLIC, 'icons', 'elbi-192.png')}`;
  body = body.replaceAll('/icons/elbi-192.png', icon);

  const drop = [
    // Public-domain films come from the Internet Archive, which needs a server
    // to fetch and re-stream them.
    /\s*<a href="\/discover"[^>]*>[^<]*<\/a>/,
    // Both of these end in a path on a filesystem that is not there.
    /\s*<button class="tab" data-tab="scan"[^>]*>[^<]*<\/button>/,
    /\s*<button class="tab" data-tab="url"[^>]*>[^<]*<\/button>/,
  ];
  for (const pattern of drop) {
    if (!pattern.test(body)) throw new Error(`markup to remove was not found: ${pattern}`);
    body = body.replace(pattern, '');
  }

  body = body.replace(
    /<p>Elbi — your own library\.[^<]*<\/p>/,
    '<p>Elbi — the hosted copy. Everything here runs in this browser; your own films stay on your own computer.</p>',
  );

  return body.trim();
}

// --------------------------------------------------------------------------
// the app

function script() {
  const sources = {};
  for (const file of fs.readdirSync(path.join(PUBLIC, 'js')).filter((f) => f.endsWith('.js'))) {
    sources[file] = read(PUBLIC, 'js', file);
  }
  // The one substitution: no server, so the server's client talks to a library
  // held in this browser instead.
  sources['api.js'] = read(ROOT, 'web', 'api.web.js');
  sources['samplelib.js'] = read(ROOT, 'web', 'samplelib.js');

  const media = mediaModule();
  sources['media.js'] = media.source;

  const built = bundle(sources, 'app.js');
  return { code: built.code, renames: built.renames, media };
}

// --------------------------------------------------------------------------
// a manifest, so an installed copy opens full screen with its own icon

function manifestSetup() {
  const manifest = JSON.parse(read(PUBLIC, 'manifest.webmanifest'));
  manifest.start_url = '.';
  manifest.scope = '.';
  manifest.icons = [
    { src: `data:image/png;base64,${b64(PUBLIC, 'icons', 'elbi-192.png')}`, sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: `data:image/png;base64,${b64(PUBLIC, 'icons', 'elbi-512.png')}`, sizes: '512x512', type: 'image/png', purpose: 'any' },
  ];
  // A manifest link only counts in the head, and the page is delivered as a
  // fragment, so it is put there on the way past.
  return `(function () {
  var link = document.createElement('link');
  link.rel = 'manifest';
  link.href = 'data:application/manifest+json;base64,' + ${JSON.stringify(Buffer.from(JSON.stringify(manifest)).toString('base64'))};
  document.head.appendChild(link);
  var touch = document.createElement('link');
  touch.rel = 'apple-touch-icon';
  touch.href = ${JSON.stringify(`data:image/png;base64,${b64(PUBLIC, 'icons', 'elbi-192.png')}`)};
  document.head.appendChild(touch);
  var meta = document.createElement('meta');
  meta.name = 'apple-mobile-web-app-capable';
  meta.content = 'yes';
  document.head.appendChild(meta);
}());`;
}

// --------------------------------------------------------------------------

const app = script();
const page = `<title>Elbi</title>
<style>
${styles()}
</style>

${markup()}

<script>
${manifestSetup()}
</script>
<script>
window.ELBI_HOSTED = true;
${app.code}
</script>
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, page);

const mb = (n) => `${(n / 1024 / 1024).toFixed(2)} MB`;
console.log(`dist/elbi.html — ${mb(Buffer.byteLength(page))}`);
console.log(`  app         ${mb(app.code.length)}`);
console.log(`  media       ${mb(app.media.bytes)} in ${app.media.count} files, base64 in the page`);
if (app.renames.length) {
  console.log('  renamed while flattening:');
  for (const line of app.renames) console.log(`    ${line}`);
}
if (Buffer.byteLength(page) > 15.5 * 1024 * 1024) {
  throw new Error('the page is close to the 16 MB limit — shorten or re-encode the sample clips');
}
